---
name: Bug report
about: Create an issue if anything doesn't appear to be working right.
title: ''
labels: bug
assignees: ''

---

**Small description**

**Expected result**

**Actual result with screenshot**
If you get an unexpected error, please include the full stack trace that you get with `Ctrl-E`.

**Steps to reproduce with sample data and a .vd**
First try reproducing without any user configuration by using the flag `-N`.
e.g. `echo "abc" | vd -f txt -N`

Please attach the commandlog (saved with `Ctrl-D`) to show the steps that led to the issue.
See [here](http://visidata.org/docs/save-restore/) for more details.

**Additional context**
Please include the version of VisiData and Python.
Can you reproduce your bug in the latest version of VisiData, which is v3.0.2?
